name: publish

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: login
        run: podman login ghcr.io --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }}
      - name: build
        run: podman build --file containerfile --tag ghcr.io/starr-dust/silverblue:latest .
      - name: push
        run: podman push ghcr.io/starr-dust/silverblue:latest
